# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:11
from __future__ import unicode_literals

import common.utils.common_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint')),
                ('desc', models.TextField(verbose_name='API Description')),
                ('is_auth_required', models.BooleanField(verbose_name='Auth?')),
                ('note', models.TextField(blank=True, null=True, verbose_name='API note')),
                ('method', models.IntegerField(choices=[(1, 'HTTP GET request method'), (2, 'HTTP POST reqeust method'), (3, 'HTTP PUT request method'), (4, 'HTTP PATCH request method'), (5, 'HTTP DELETE request method')], default=1, verbose_name='Request Method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIParameter',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=100, verbose_name='Parameter Name')),
                ('parameter_type', models.CharField(choices=[(1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'String'), (5, 'Array'), (6, 'Object/Dict'), (7, 'File')], default=2, max_length=50, verbose_name='Request Parameter value type')),
                ('desc', models.TextField(verbose_name='Parameter Description')),
                ('version', models.CharField(default='v1', max_length=20, verbose_name='API Version Number')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api_doc.APIInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIResult',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('result_type', models.CharField(choices=[(1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'String'), (5, 'Array'), (6, 'Object/Dict'), (7, 'File')], default=2, max_length=50, verbose_name='API Returned Field value type')),
                ('desc', models.TextField(verbose_name='Field Description')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_doc.APIInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=100, verbose_name='App name')),
                ('desc', models.TextField(verbose_name='App description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='api_doc.APP'),
        ),
    ]
