# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 21:16
from __future__ import unicode_literals

import common.utils.common_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestParameter',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('is_required', models.BooleanField(verbose_name='是否必要?')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'API请求参数',
                'verbose_name_plural': 'API请求参数',
            },
        ),
        migrations.CreateModel(
            name='APIResponseParameter',
            fields=[
                ('object_id', models.UUIDField(default=common.utils.common_utils.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update time')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is active?')),
                ('is_required', models.BooleanField(verbose_name='是否必要?')),
                ('note', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': 'API返回数据',
                'verbose_name_plural': 'API返回数据',
            },
        ),
        migrations.RemoveField(
            model_name='apiresult',
            name='api',
        ),
        migrations.AlterModelOptions(
            name='apiinfo',
            options={'verbose_name': 'API详情', 'verbose_name_plural': 'API详情'},
        ),
        migrations.AlterModelOptions(
            name='apiparameter',
            options={'verbose_name': 'API参数', 'verbose_name_plural': 'API参数'},
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': '应用', 'verbose_name_plural': '应用'},
        ),
        migrations.RemoveField(
            model_name='apiparameter',
            name='api',
        ),
        migrations.RemoveField(
            model_name='apiparameter',
            name='version',
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='resource_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='资源名称'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='version',
            field=models.CharField(default='v1', max_length=20, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='apiparameter',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='api_doc.APP', verbose_name='所属应用'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='desc',
            field=models.TextField(verbose_name='API描述'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='endpoint',
            field=models.CharField(max_length=200, verbose_name='请求URL'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='is_auth_required',
            field=models.BooleanField(verbose_name='需要验证?'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='method',
            field=models.IntegerField(choices=[(1, 'HTTP GET'), (2, 'HTTP POST'), (3, 'HTTP PUT'), (4, 'HTTP PATCH'), (5, 'HTTP DELETE')], default=1, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='apiparameter',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='参数描述'),
        ),
        migrations.AlterField(
            model_name='apiparameter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='apiparameter',
            name='parameter_type',
            field=models.IntegerField(choices=[(1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'String'), (5, 'Array'), (6, 'Object/Dict'), (7, 'File'), (8, 'UUID'), (9, 'URL'), (10, 'DateTime'), (11, 'TimeStamp')], default=4, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='app',
            name='desc',
            field=models.TextField(verbose_name='应用描述'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=100, verbose_name='应用名称'),
        ),
        migrations.DeleteModel(
            name='APIResult',
        ),
        migrations.AddField(
            model_name='apiresponseparameter',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_doc.APIInfo', verbose_name='所属API'),
        ),
        migrations.AddField(
            model_name='apiresponseparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retapis', to='api_doc.APIParameter', verbose_name='字段名称'),
        ),
        migrations.AddField(
            model_name='apirequestparameter',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api_doc.APIInfo', verbose_name='所属API'),
        ),
        migrations.AddField(
            model_name='apirequestparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqapis', to='api_doc.APIParameter', verbose_name='参数名称'),
        ),
    ]
