# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_doc', '0002_auto_20170717_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='test')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apiparameter',
            name='parameter_type',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'Float'), (3, 'String'), (4, 'Date'), (5, 'Array'), (6, 'Dict'), (7, 'Boolean')], default=3, verbose_name='参数类型'),
        ),
    ]
